rvm:
  - 1.9.3
  - 2.1.2
  - 2.1.3
services:
  - elasticsearch
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script: "bundle exec rspec"
language: "ruby"
notifications:
  email: false